name: Robot
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  robot:
    name: Run rf tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Robot Framework
        run: |
          pip install robotframework

      - name: Run Robot Tests
        run: |
          robot --outputdir results -i test ./tests/robot

      - name: Prepare Pages content
        run: |
          mkdir pages
          cp results/log.html pages/

      - name: Upload Robot Test Results
        uses: actions/upload-artifact@v6
        with:
          name: result
          path: results

      - uses: actions/upload-pages-artifact@v5
        with:
          path: pages

  deploy:
    needs: robot
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
      log_url: ${{ steps.urls.outputs.log_url }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v5
        id: deployment
